

"""
Helper functions to map names such as 'Watauga', 'Linville', etc to salesforce ID numbers
"""

import pandas as pd
import geopandas as gpd

# test_properties = gpd.read_file('/Users/ep9k/Desktop/test_properties.gpkg')

def map_nearest_feature_name(df):
    pass


def map_creek_name(df):
    df.loc[df['CREEK_LOOKUP__C'] == 'Adams Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg2tEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Aho Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg2uEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Andy Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg2vEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Arnold Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg2wEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Asher Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg2xEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Ashley Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg2yEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Atchison Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg2zEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Avery Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg30EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Bailey Camp Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg31EAA'
    df.loc[df['CREEK_LOOKUP__C'] == "Baird's Creek", 'CREEK_LOOKUP__C'] = 'a2E3u000000fg32EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Baker Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg33EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Ballew Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg34EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Banjo Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg35EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Barry Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg36EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Bear Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg37EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Bear Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg38EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Bear Den Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg39EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Beaver Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3AEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Beaver Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3BEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Beaverdam Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3CEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Bee Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3DEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Bee Cove Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3EEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Bee Tree Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3FEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Beech Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3GEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Ben Bolen Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3HEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Berry Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3IEAQ
    df.loc[df['CREEK_LOOKUP__C'] == 'Big Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3JEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Big Dry Run', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3KEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Big Horse Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3LEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Big Laurel Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3MEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Big Sandy Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3NEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Big Windfall Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3OEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Bill White Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3PEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Birchfield Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3QEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Black Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3REAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Black Mountain Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3SEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Blackman Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3TEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Bledsoe Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3UEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Blevins Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3VEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Blood Camp Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3WEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Boomer Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3XEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Boone Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3YEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Boone Camp Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3ZEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Boone Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3aEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Boone Fork', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3bEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Bowlin Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3cEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Bowling Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3dEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Brickyard Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3eEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Brown Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3fEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Browns Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3gEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Brush Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3hEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Brush Fork', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3iEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Brushy Fork', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3jEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Buck Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3kEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Buck Ridge Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3lEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Buckeye Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3mEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Buffalo Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3nEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Bulldog Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3oEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Bullhead Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3pEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Bunton Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3qEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Bunton Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3rEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Buttermilk Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3sEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Cabbage Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3tEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Call Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3uEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Camp Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3vEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Campbell Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3wEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Cannon Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3xEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Capley Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3yEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Carriger Spring Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg3zEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Carroll Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg40EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Cheek Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg41EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Chestnut Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg42EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'China Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg43EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Christian Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg44EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Clark Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg45EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Clark Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg46EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Clarke Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg47EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Claybank Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg48EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Clear Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg49EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Clear Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4AEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Clingman Mine Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4BEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Cobb Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4CEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Cold Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4DEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Cole Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4EEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Cook Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4FEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Copeland Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4GEAQ
    df.loc[df['CREEK_LOOKUP__C'] == 'Copley Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4HEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Corn Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4IEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Cornett Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4JEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Corum Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4KEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Couches Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4LEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Cove Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4MEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Cow Camp Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4NEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Crab Fork', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4OEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Craborchard Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4PEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Cranberry Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4QEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Creasey Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4REAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Cress Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4SEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Crooked Banch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4TEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Crossnore Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4UEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Curtis Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4VEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Cut Laurel Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4WEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Dale Neely Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4XEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'David Blevins Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4YEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Days Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4ZEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Dennis Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4aEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Dixon Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4bEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Doe Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4cEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Doe Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4dEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Doe Fork', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4eEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Dog Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4fEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Doll Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4gEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Doubles Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4hEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Drake Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4iEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Draught Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4jEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Dry Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4kEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Drystone Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4lEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Duck Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4mEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Dugger Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4nEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Dutch Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4oEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Dye Leaf Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4pEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'E H Phillippi', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4qEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Eager Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4rEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Elk Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg4zEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Ellison Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg50EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Evans Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg51EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Ezra Fork', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg52EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Fall Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg53EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Fall Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg54EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Fees Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg55EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Fenner Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg56EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Fiddlers Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg57EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Five Poplar Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg58EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Flannery Fork', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg59EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Flat Spring Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5AEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Flat Springs Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5BEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Flat Top Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5CEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Flattop Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5DEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Flowers Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5EEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Forest Grove Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5FEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Forge Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5GEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Fork Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5HEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Fork Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5IEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Foster Springs Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5JEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Furnace Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5KEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Gap Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5LEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Gap Run', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5MEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Gentry Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5NEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Gentry Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5OEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'George Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5PEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'George Gap Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5QEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Glade Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5REAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Goldmine Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5SEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Goose Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5TEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Gouge Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5UEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Grassy Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5VEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Grassy Gap Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5WEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Graybeal Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5XEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Green Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5YEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Green Mountain Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5ZEAQ'
    df.loc[df['CREEK_LOOKUP__C'] == 'Green Mountain Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5aEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Green Ridge Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5bEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Greer Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5cEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Gregg Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5dEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Grindstone Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5eEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Groundhop Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5fEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Hall Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5gEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Hamby Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5hEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Hampton Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5iEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Handpole Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5jEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Hanging Rock Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5kEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Harbin Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5lEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Harrison Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5mEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Haw Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5nEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Hayes Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5oEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Heaberlin Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5pEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Heaton Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5qEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Heaton Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5rEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Helton Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5sEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Henson Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5tEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Hickorynut Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5uEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'High Trestle Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5vEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Hignite Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5wEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Hillside Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5xEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Hodges Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5yEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Hog Camp Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg5zEAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Holloway Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg60EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Holly Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg61EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Horn Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg62EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Horney Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg63EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Horse Bottom Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg64EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Horse Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg65EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Horse Cove Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fg66EAA'
    df.loc[df['CREEK_LOOKUP__C'] == 'Horse Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCZEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Hoskin Fork', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCaEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Howard Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCbEAI'
    df.loc[df['CREEK_LOOKUP__C'] == "Howard's Creek", 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCcEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Ingram Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCdEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Isaae Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCeEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'James Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCfEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Jenkins Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCgEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Jenny Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgChEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Jerd Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCiEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Jerry Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCjEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Jewel Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCkEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Jim Wright Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgClEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Joes Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCmEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Johnson Blevins Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCnEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Jones Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCoEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Jones Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCpEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Justice Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCqEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Katy Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCrEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Keller Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCsEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Kentucky Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCtEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Kilby Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCuEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Kirby Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCvEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Lance Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCwEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Laurel Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCxEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Laurel Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCyEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Laurel Fork', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgCzEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Laxon Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgD0EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Lee Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgD1EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Mulberry Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgD2EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Left Prong Hampton Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgD3EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Leroy Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgD5EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Linville Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgD6EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Lipford Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgD7EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Beaverdam Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgD8EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Buffalo Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgD9EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Cove Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDAEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDBEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Dry Run', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDCEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Elk Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDDEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Gap Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDEEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Glade Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDFEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Helton Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDGEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Henson Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDHEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Horse Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDIEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Laurel Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDJEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Laurel Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDKEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Naked Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDLEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Peak Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDMEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Phoenix Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDNEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Piney Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDOEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Plumtree Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDPEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Whiteoak Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDQEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Little Windfall Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDREAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Locust Knob Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDSEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Long Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDTEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Long Hope Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDUEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Long Shoal Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDVEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Lost Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDWEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Lumpkin Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDXEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Lunt Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDYEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Mack Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDZEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Maine Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDaEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Mains Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDbEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Maple Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDcEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Martin Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDdEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Martin Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDeEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'McCann Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDfEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'McEwen Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDgEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'McKinney Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDhEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'McQueen Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDiEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Meadow Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDjEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Meadow Fork', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDkEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Meat Camp Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDlEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Middle Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDmEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Milam Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDqEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Mill Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDrEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Mill Timber Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDsEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Milligan Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDtEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Millpond Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDuEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Mine Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDvEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Moccasin Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDwEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Mollie Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDxEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Monkey Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDyEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Moody Mill Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgDzEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Moreland Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgE0EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Morgan Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgE1EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Morton Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgE2EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Mud Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgE3EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Muddy Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgE4EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Mutton Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgE5EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Naked Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgE6EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Nathans Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgE7EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'New Years Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgE8EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'No Head Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgE9EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Norris Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEAEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Norris Fork', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEBEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Nowhere Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEJEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Obids Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEKEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Old Field Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgELEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Old Field Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEMEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Old Fields Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgENEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Owens Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEOEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Owl Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEPEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Palmer Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEQEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Parks Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEREAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Patrick Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgESEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Payne Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgETEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Peak Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEUEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Peavine Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEVEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Penley Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEWEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Phillips Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEXEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Phillips Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEYEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Pierce Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEZEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Pigeonroost Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEaEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Pine Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEbEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Pine Mountain Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEcEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Pine Orchard Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEdEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Pine Run', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEeEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Pine Swamp Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEfEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Piney Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEgEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Piney Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEhEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Piney Fork', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEiEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Plumtree Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEjEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Poga Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEkEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Pond Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgElEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Potato Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEmEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Potter Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEnEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Pounding Mill Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEoEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Powdermill Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEpEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Prathers Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEqEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Puckett Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgErEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Puncheon Camp Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEsEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Pyatt Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEtEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Raccoon Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEuEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Race Path Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEvEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Reece Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEwEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Reese Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgExEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Reeves Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEyEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Reservoir Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgEzEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Rhinestone Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgF0EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Rich Gap Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgF1EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Rich Hill Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgF2EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Rich Mountain Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgF3EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Ripshin Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgF4EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Rittle Fork', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgF5EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Roan Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgF6EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Roaring Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgF7EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Roaring Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgF8EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Roaring Fork', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgF9EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Rock Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFAEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Rock Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFBEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Rockhouse Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFCEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Rocky Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFDEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Roten Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFEEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Roundabout Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFFEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Row Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFGEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Rube Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFHEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Rush Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFIEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Sally Cove Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFJEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Sandbank Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFKEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Sandpit Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFLEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Sawmill Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFMEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Sawyer Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFNEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Scott Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFOEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Seng Cove Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFPEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Shanty Spring Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFQEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Sharp Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFREAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Shaw Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFSEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Shawneehaw Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFTEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Shell Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFUEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Shingletown Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFVEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Shippy Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFWEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Shoemaker Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFXEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Shook Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFYEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Shoun Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFZEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Sidney Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFaEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Silas Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFbEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Silas Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFcEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Simcox Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFdEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Simerly Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFeEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Sims Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFfEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Sink Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFgEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Skalley Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFhEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Slabtown Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFiEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Slimp Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFjEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Smith Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFkEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Smitty Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFlEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Snyder Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFmEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Soup Bean Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFnEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'South Beaver Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFoEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Lewis Fork', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFuEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Spanish Oak Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFvEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Spear Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFwEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Spice Bottom Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFxEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Spice Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFyEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Spruce Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgFzEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Squirrel Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgG0EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Stacey Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgG1EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Stagg Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgG2EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Stalcup Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgG3EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Stamey Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgG4EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Stanley Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgG5EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'State Line Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgG6EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Steve Phillippi Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgG7EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Stone Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgG8EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Stone Mountain Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgG9EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Stone Mountain Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGAEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Stony Fork', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGBEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Storey Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGCEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Stout Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGDEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Sugar Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGEEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Sugar Hollow Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGFEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Sugar Tree Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGGEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Sumpter Cabin Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGHEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Swift Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGIEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Thaxon Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGJEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Thomas Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGKEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Three Top Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGLEAY
    df.loc[df['CREEK_LOOKUP__C'] == 'Threemile Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGMEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Thunderhole Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGNEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Tiger Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGOEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Timothy Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGPEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Tom Baker Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGQEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Toms Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGREAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Town Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGSEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Trigger Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGTEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Trim Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGUEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Trivett Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGVEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Trout Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGWEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Turkeypen Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGXEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Valley Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGZEAY'
    df.loc[df['CREEK_LOOKUP__C'] == 'Vanderpool Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGaEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Vaught Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGbEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Vaught Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGcEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Vile Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGdEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Wallace Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGeEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Ward Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGfEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Waterfalls Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGgEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Waters Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGhEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Watson Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGiEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Webb Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGjEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Whitaker Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGqEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'White Pine Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGrEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'White Spring Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGsEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Whitehead Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGtEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Whitehead Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGuEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Whiteoak Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGvEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Wildcat Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGwEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Wilson Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGxEAI'
    df.loc[df['CREEK_LOOKUP__C'] == "Winkler's Creek", 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGyEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Wolf Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgGzEAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Wolfden Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgH0EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Wolfpen Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgH1EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Woodard Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgH2EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Woodward Branch', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgH3EAI'
    df.loc[df['CREEK_LOOKUP__C'] == 'Worley Creek', 'CREEK_LOOKUP__C'] = 'a2E3u000000fgH4EAI'

    return df




def map_custom_area_name(df);:
    pass


def map_zone_name(df):
    pass


def map_county_name(df):
    df.loc[df['COUNTY_NAME_LOOKUP__C'] == 'Ashe', 'new_county'] = 'a2E3u000000fSaIEAU'
    df.loc[df['COUNTY_NAME_LOOKUP__C'] == 'Avery', 'new_county'] = 'a2E3u000000fSaSEAU'
    df.loc[df['COUNTY_NAME_LOOKUP__C'] == 'Alleghany', 'new_county'] = 'a2E3u000000fSaXEAU'
    df.loc[df['COUNTY_NAME_LOOKUP__C'] == 'Caldwell', 'new_county'] = 'a2E3u000000fSaJEAU'
    df.loc[df['COUNTY_NAME_LOOKUP__C'] == 'Watauga', 'new_county'] = 'a2E3u000000fSaYEAU'
    df.loc[df['COUNTY_NAME_LOOKUP__C'] == 'Wilkes', 'new_county'] = 'a2E3u000000fSaTEAU'
    df.loc[df['COUNTY_NAME_LOOKUP__C'] == 'Johnson', 'new_county'] = 'a2E3u000000fSaZEAU'
    df.loc[df['COUNTY_NAME_LOOKUP__C'] == 'Carter', 'new_county'] = 'a2E3u000000fSacEAE'
    df.loc[df['COUNTY_NAME_LOOKUP__C'] == 'Out of County', 'new_county'] = 'a2E3u000000fUvcEAE'

    return df


def map_subdivision_name(df);:
    pass



# df1 = convert_county_name(test_properties)
    
    
    


