#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun  2 15:58:48 2020

@author: ep9k
"""


import geopandas as gpd
import pandas as pd

import BRE_Workflow_Functions as bwf




"""This is taking all zone 6a parcels, finding the vacant land, then doing some custom
price filters to get different results for Joel than the regular zones filters """

#1.
#Read in zone6a_all_parcels

zone6a_parcels = gpd.read_file('/Users/ep9k/Desktop/zone6a_all_parcels.gpkg')


#drop duplicates
zone6a_parcels = zone6a_parcels.drop_duplicates(subset='parno', keep='first')


#2.
#Create Vacant Land Property Type

# #create 'Property Type' column and populate with true/false values
# all_2019_parcels['Property Type'] = all_2019_parcels['landval'] == all_2019_parcels['parval']
zone6a_parcels['Property Type'] = zone6a_parcels['landval'] == zone6a_parcels['parval']

# #change true/false values to 'Vacant Land' or no value.
zone6a_parcels.loc[(zone6a_parcels['Property Type'] == True), 'Property Type'] = 'Vacant Land'
zone6a_parcels.loc[(zone6a_parcels['Property Type'] == False), 'Property Type'] = ''

# ##Label others from Watauga County using parusedesc columnn. Now there are 94778 vacant land parcels (added 190 parcels)
zone6a_parcels = bwf.property_type_column(zone6a_parcels)


# 3.
#Make Vacant Land dataframe

vacant_land_df = zone6a_parcels[zone6a_parcels['Property Type'] == 'Vacant Land']

#apply price and area filters, these are unique to zone 6a
vacant_land_df = bwf.zone_6a_vacant_land_filters(vacant_land_df)
#HERE WE ARE LEFT WITH 267 VACANT LAND PARCELS

# 4.
#remove undesireable zoning types from 'parusedesc' column (Watauga Only)
bad_parusedesc = ['COMMERCIAL AUXILIARY IMPROVEMENT','COMMERCIAL LAND VACANT','COMMERCIAL UNDER CONSTRUCTION','EDUCATION','EDUCATION RELIGIOUS','ELECTRIC UTILITY','GOVERNMENT','HEALTH SPA','INDUSTRIAL TRACT VACANT','RELIGIOUS','UTILITY VACANT LAND','WAREHOUSE WITH INTERIOR OFFICE SPACE']

for parusedesc in bad_parusedesc:
    vacant_land_df.drop(vacant_land_df[vacant_land_df['parusedesc'] == parusedesc].index, inplace=True)
#down to 4596 parcels


#drop owner names which are clearly commercial, industrial, etc.
bad_owner_names = ['WATAUGA COUNTY','WATAUGA BUILDING SUPPLY INC.','WATAUGA MEDICAL CENTER INC','WATAUGA OPPORTUNITIES INC.','REYNOLDS BLUE RIDGE PROP OWNERS ASSO INC','REYNOLDS BLUE RIDGE PROPERTY OWNERS ASSN','APPALACHIAN STATE UNIV FOUND,MCKINNEY ALUMNI CENTER','APPALACHIAN STATE UNIV FOUND,MCKINNEY ALUMNI CENTER','APPALACHIAN STATE UNIVERSITY FOUNDATION',
                    'BOARD OF TRUSTEES OF THE ENDOWMENT FUND ,.APPALACHIAN STATE UNIVERSITY BOARD OF T','BOARD OF TRUSTEES OF THE ENDOWMENT FUND,.APPALACHIAN STATE UNIVERSITY BOARD OF T','NORTH CAROLINA, STATE OF','STATE EMPLOYEES CREDIT UNION','STATE OF NC','STATE OF NC PROPERTY OFFICE','STATE OF NC,STATE PROPERTY OFFICE','STATE OF NORTH CAROLINA',
                    'STATE OF NORTH CAROLINA C/O STATE PROPERTY OFFICE','STATE OF NORTH CAROLINA THE','UNITED STATED OF AMERICA','UNITED STATES AGRICULTURE','UNITED STATES DEPT OF INTERIOR','UNITED STATES FOREST SERVICE','UNITED STATES OF AMERICA','NATURE CONSERVANCY','NATURE CONSERVANCY THE','NATURE CONSERVANCY, THE','NC NATURE CONSERVANCY','AVERY DEVELOPMENT CORPORATION',
                    'COUNTY OF AVERY','COUNTY OF ASHE','COUNTY OF ASHE THE','CALDWELL COUNTY','ASHE COUNTY OF','ASHE COUNTY BOARD OF EDUCATION','WATAUGA COUNTY','NC','NC DEPARTMENT OF TRANSPORTATION','CHESTER BAR OF NORTH CAROLINA','USA','OLEANDER COMPANY THE','APPALACHIAN SKI MTN INC','APPALACHIAN ADVENT CHRISTIAN ASSOCIATION','APPALACHIAN STATE UNIVERSITY',
                    'LEES MC RAE COLLEGE FIXED ASSETS COORDINATOR','LEES MC RAE COLLEGE, INC','BALD MOUNTAIN BAPTIST CHURCH INC','BALD MOUNTAIN TRUST THE (TRUSTEES)','BANNER ELK PRESBYTERIAN CHURCH','DIVINE HOPE BAPTIST CHURCH','MORAVIAN CHURCH IN AMERICA S.P.','NORTH CAROLINA DEPARTMENT OF TRANSPORTATION','FOOTHILLS CONSERVANCY OF NORTH CAROLINA','LANTANA FLORIDA CORPORATION',
                    'BLOWING ROCK REALTY & INS INC','CALDWELL REALTY','PRY REALTY LLC','WEST JEFFERSON REALTY LLC','WILBERN REALTY & INVESTMENT CO','YOUNG MEN''S CHRISTIAN ASSOCIATION','VILLAGE OF SUGAR MOUNTAIN','SUGAR MOUNTAIN RESORT INC','SOUTHERN APPALACHIAN HIGHLANDS CONSERVANCY','BLUE RIDGE CONSERVANCY','BLOWING ROCK COUNTRY CLUB','TOWN OF BLOWING ROCK',
                    'INDEPENDENCE LUMBER COMPANY INC.','JEFFERSON DEVELOPMENT CORPORATION','JENSEN HOLDINGS, INC A FLORIDA CORP.','L&S LAND CORPORATION','ELK CREEK DEVELOPMENT COMPANY OF BANNER ELK, LLC','FIRST CITIZENS BANK & TRUST COMPANY','GENTRY CONSTRUCTION COMPANY INC.','R & R BUILDERS COMPANY OF NORTH CAROLINA','R&R BUILDERS COMPANY OF NORTH CAROLINA','THE HIGHLANDER COMPANY',
                    'HIGH POINT BANK & TRUST CO SUCCESSOR TR,THE T HENRY WILSON FAMILY TRUST', 'AVERY REAL PROPERTIES, LLC','CFFC REAL ESTATE LLC','GENTRY FAMILY REAL ESTATE, LLC','GRIFFITH, E C CO REALTORS','B JOYCE HATFIELD REVOCABLE LIVING TRUST','COY BOLICK LIVING TRUST,C/O DAVID AND JULIE JONES','DODSON LIVING TRUST','DOUGLAS L MCGUIRE LIVING TRUST','GLENN SUSAN LIVING TRUST',
                    'GRACE K HUTCHINS LIVING TRUST,KILKELLY, GARY AND JOAN','GREYSTONE LIVING TRUST','HAGLER, ROSS TRUSTEE OF THE HAGLER, DOROTHY LIVING TRUST','LEMLY MINNIE C (LIVING TRUST) (1/2)','LILLIAN TURCHIN LIVING TRUST','LINDA J HODGES LIVING TRUST,HODGES, LINDA J','MARY S HORN LIVING TRUST,HORN, MARY S TR','MICHAEL M MILLER REVOCABLE LIVING TRUST','RONALD J STANLEY LIVING TRUST',
                    'STONE, HERBERT S. & BETTY W. STONE LIVING TRUST','THOMAS A BARRETT LIVING TRUST','TRIPLETT, JIM W,.JIMMY W TRIPLETT LIVING TRUST','THOMAS L GREER LIVING TRUST,THGREER, THOMAS L \TR','WILLA JEAN BROWN LIVING TRUST','WILLIAM J. WILLIAMSON, III LIVING TRUST','WILLIAM STEWART PENICK LIVING TRUST,PENICK, STEWART','BAKER ARVIL R & JOYCE G (L/E)','BARE HAZEL (L/E)',
                    'BARKER CLARA (L/E)','BLACKBURN ALENE (L/E)','BUSIC, RODNEY F. JR. & SANDRA L. L/E','CHURCH, PAUL E. JR.  ET AL L/E','DAVIS, HAROLD RANDALL & PEGGY LORAINE L/E','DILLARD GLADYS  (L/E)','DUNCAN, PETTY CHOATE L/E','GREENE HATTIE JO (L/E)','HART STEVE (L/E)','JOINES, KATHRYN L/E','LITTLE KATHLEEN (L/E)','LITTLE KATHLEEN (L/E) & MARTIN','LITTLE KATHLEEN E (L/E)',
                    'LONG CLAYTON & W G LONG (L/E)','MABE, EVERETTE J. & SHIRLEY S. L/E','MILLER ROBERT W (L/E)','REEVES, OSCAR A. L/E','ROUPE, LIZABETH R. L/E','SOPER BETTY CAROLYN (L/E)','STURGILL JEAN (L/E)','TESTERMAN CORINE D (L/E)','TUCKER, BETTY B. L/E','WAGONER, JAMES L/E','WEAVER LORETTA J (L/E)','LANGSTON, CRAIG LIFE ESTATE,JAMES, J DIANE',
                    'STORIE, MARVIN K (LIFE ESTATE),SIGMON, MARGARET E (LIFE ESTATE)','TRIVETTE, ALICE(LIFE ESTATE),TRIVETTE, BOBBY B']

for owner_name in bad_owner_names:
    vacant_land_df.drop(vacant_land_df[vacant_land_df['ownname'] == owner_name].index, inplace=True)


#THIS LEAVES US WITH 265 VACANT LAND PARCELS

# 5.
# Export to geopackage for use in QGIS
# vacant_land_df = gpd.GeoDataFrame(vacant_land_df, geometry='geometry')
# vacant_land_df.to_file('/Users/ep9k/Desktop/vacant_land_6a.shp')


